on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.8.8', '3.9.4', '3.9.5', '3.6.3' ]

    name: Maven ${{ matrix.maven }} sample

    steps:

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.9.0
        with:
          java-version: 17
          maven-version: ${{ matrix.maven }}

      - run: mvn -v
