on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.8.8', '3.9.4' ]

    name: Maven ${{ matrix.maven }} sample

    steps:

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@1.10.0
        with:
          java-version: 8
          maven-version: ${{ matrix.maven }}

      - run: mvn -V ...
